### ISSUE TITLE
Use `get_studio_settings` to ensure settings caching

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-usd#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently, ask the server for the settings on every call to ensure that they are updated and not "static" This avoids having to restart the launcher when a setting on the server changes 

@iLLiCiTiT proposed using `get_studio_settings` as an alternative. 

- [ ] find out if `get_studio_settings` is cached in a way that still solves @BigRoy request for "dynamically" updating settings 

### How would you imagine the implementation of the feature?

Depending on how the caching is implemented, it might be an option to build a simple `data class` that conveniently exposes all the settings.
Use `get_studio_settings` in the background to get the settings. If we make a change, we should update the data class. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by Lypsolon** [comment]
@BigRoy i believe this is fixed with the last merge you did ? but wanted to ask you to be sure.

**Comment by BigRoy** [comment]
It does use a cache, its cache lives for 10s - as far as I know.
