### ISSUE TITLE
Pyblish Plugin that uses the Pinning suport for Usd Stage Reselution 

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-usd#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently, the publish plugins do not use the Pinning support on the farm, thereby over-utilising the server. 

### How would you imagine the implementation of the feature?

[Ayon Usd Resolver Pinning Docs](https://github.com/ynput/ayon-usd-resolver/blob/feature/23-feature-request_pinn_file_loading/Docs/Ayon_Docs/Dev_Docs.md#pinning)

The resolver comes with a pinning feature that can be enabled via Env variables. 
It's a startup feature and is currently not intended to be changed on runtime. 

The addon would need to set the env variables before starting the job and then start the job. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by antirotor** [comment]
This is in process here https://github.com/ynput/ayon-usd/pull/41/
