### ISSUE TITLE
Unable to launch some applications for which there is no valid USD resolver

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-usd#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

As far as I know the LakeFS distribution used currently does not come (yet?) with resolvers for Nuke and Blender, even though they _are_ listed for the pre resolver init launch hook. Which means that those will never be able to launch.

### Expected Behavior:

We should allow a studio to decide WHICH applications they want to enforce the USD resolver for - and make it very trivial to enable/disable that.

I think we're best off having a settings that allows you to add/remove applications from a list for something like:

- [x] Maya (required)
- [x] Houdini (required)
- [ ] Nuke
- [x] Blender (allow launch without resolver)
- [ ] Unreal 

_note that these checkboxes are just for the "example" - they are not to highlight which have been fixed or work or whatever_

Where an admin can easily say add an application, e.g. Nuke and allow to enable/disable it globally (like never run, or try to run with resolver)... and maybe have an additional option there that allows you to still run it (with just a logged warning) if no matching resolver was found.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Launch Blender with AYON-USD enabled.

![image](https://github.com/user-attachments/assets/72be9bc2-b0e7-477e-b9bc-483e571d5490)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Additional context:

The apps that require it now are defined via this set of applications: https://github.com/ynput/ayon-usd/blob/4f6202ffea3b55dc70da140420518d81c005b0b4/client/ayon_usd/hooks/pre_resolver_init.py#L16

However, with the logic I described in this issue above that would be removed and run over ALL application and instead do a check in `execute()` using the project settings to define whether an application would need a resolver or not.

**Comment by Lypsolon** [comment]
fair point we should remove the groups that arent on LakeFs yet

**Comment by BigRoy** [comment]
> fair point we should remove the groups that arent on LakeFs yet

That - but I also feel like a studio should allow disabling for certain hosts via settings. And, I think if we allow launching just fine but with a warning might be a better approach too.

**Comment by Lypsolon** [comment]
> That - but I also feel like a studio should allow disabling for certain hosts via settings. And, I think if we allow launching just fine but with a warning might be a better approach too.

hmm: there are multiple thoughts in my mind about that. 
1: When a Resolver is Disabled should the contribution via Url be Disabled? 
2: how do we handle loading stages that have URI? we could just go and let it error but im not sure if that enough of an solution. could be annoying for Artists ? 
3: Can we Show errors / warnings in the server ui if you disable resolver for a app while still having URI contribution on ? 

with that said. im gonna create a branch and remove the app grps that we dont support yet and when we made a decision on how to do the Enable Dissable thing a second one that implements that. 
Thanks for noticing.

**Comment by BigRoy** [comment]
> 1: When a Resolver is Disabled should the contribution via Url be Disabled?

Fair question - but I'd say, let's first hit the case that a studio _actually_ wants to somehow mix that in an odd way. It's not impossible to match those via profiles, but I'd rather not if we can avoid it.

> 2: how do we handle loading stages that have URI? we could just go and let it error but im not sure if that enough of an solution. could be annoying for Artists ?

Yes. Error, that's up to responsibility of the studio at that point. Once you're going URIs - you'll want to load with resolver. If you can't have the resolver for some app, their issue then since it's a necessity for resolving them.

> 3: Can we Show errors / warnings in the server ui if you disable resolver for a app while still having URI contribution on ?

We can log a warning in the console on the machine itself (however, those do not standout to the artist usually but only going to console to debug there - which admittedly I think is what we want for now.) Regarding having these events send to the ayon server, they won't by default. I'm not sure what mechanisms it offers to submit that to the server.

I'm more coming from the point that I assume more people will hate that they can't launch software at all, than that maybe the resolver doesn't work.

**Comment by Lypsolon** [comment]
> Fair question - but I'd say, let's first hit the case that a studio _actually_ wants to somehow mix that in an odd way. It's not impossible to match those via profiles, but I'd rather not if we can avoid it.

good point. but do we want to allow for mix and match or would it be convenient to disable / enable resolver in general instead of per app ? 

> We can log a warning in the console on the machine itself (however, those do not standout to the artist usually but only going to console to debug there - which admittedly I think is what we want for now.) Regarding having these events send to the ayon server, they won't by default. I'm not sure what mechanisms it offers to submit that to the server.

when i said on the server i was talking about if you disable only blender we might have a Text atop of the page with "Hey that's not the best idea"; not sure if you mean the same

But if we want to allow Mixing (Honestly i dont think we should it would be better to have Enable / Disable Resolver in general in my Eyes) this might be the easy way that works. 

> I'm more coming from the point that I assume more people will hate that they can't launch software at all, than that maybe the resolver doesn't work.

that's a really good point. in general i believe we should not break an Artist Space but i get the idea and its a fair point. 

It also raises the Question what we do if we cant reach the LakeFs repo to download a Resolver.

**Comment by BigRoy** [comment]
This has been resolved by https://github.com/ynput/ayon-usd/pull/61 - now applications can launch with just warnings to the console.
