### ISSUE TITLE
Houdini 20.5 cant start because we have no resolver for it 

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-usd#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When trying to start Houdini 20.5 it will crash as we do not have a resolver for it yet. 

### Version

1.0.0

### What platform you are running on?

Windows, Linux / Centos, Linux / Ubuntu, Linux / RedHat, MacOS

### Steps To Reproduce:

1. enable usd addon 
2. open houdini 20.5 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
Resolved by https://github.com/ynput/ayon-usd/pull/61

We still do not have a resolver for it - but it will now allow launching the application.
